# 可能是解析库的原因，如果类似下面这句放到任何[]之下的话，都会被认为是[]下的所属，故类似这种没有[]的，都得放到前面来
sentry_dsn= "http://da3139a4014c431a9024a3b0b3eb9da7:c387db95d2384d83b594f984cf303420@47.99.39.114:9000/4"

[base_info]
    version = "0.1"
    name = "samh-comic"
    port = 8701
    app_id = 6

[log_info_item]
    level="debug" #debug info warn error panic fatal，正式环境用info，其他用debug
    encoding="console"     # 输出格式 console 或 json，建议正式环境用json，其他console（简洁）
    stdout=true #同时输出到控制台
    development_mode=true # 开发模式，堆栈跟踪
    path_filename = "/data1/logs/samh/comic/log.log"
    # max_size=  128    # 每个日志文件保存的最大尺寸 单位：M
    # max_backups= 30   # 日志文件最多保存多少个备份
    # max_age=     7    # 文件最多保存多少天
    compress=true

[internal_server]
    [internal_server.user]
        url="http://192.168.209.87:3020"
        time_out = 500  # millisecond

[db_arr]
    [db_arr.commerce]
        type = "mysql"
        host = "47.98.46.213"
        port = 3306
        user = "ecy"
        password = "erchiyuan"
        db_name = "commerce"
        max_conns = 20
        time_out = 300
        log_path = "/data1/logs/samh/comic/"
        log_name = "log.log"
        [db_arr.commerce.table_name]
            a = "a"
            b = "b"

[redis_item]
    network="tcp"
    addr = "127.0.0.1:6379"
    password = "abc123"
    max_retries=3
    pool_size=200
    prefix="comic:" #此服务的redis key的前缀，推荐具体格式 服务名:业务名:表名，然后里存json，这样缓存如整张表的时候就可以直接根据json中的key(对应主键)来取了
    time_out=604800 #86400*7

[redis_cluster_item]
    master_addr_arr = ["47.99.39.114:7000","47.99.39.114:7001","47.99.39.114:7002"]
    slave_addr_arr = ["47.99.39.114:7003","47.99.39.114:7004","47.99.39.114:7005"]
    password = "gUcAFcWf#Dg4He7R"
    max_retries=3
    pool_size=200
    prefix="comic:" #此服务的redis key的前缀，推荐具体格式 服务名:表名（业务名），然后里存json，这样缓存如整张表的时候就可以直接根据json中的key(对应主键)来取了
    time_out=604800 #86400*7

[web]
    http_request_timeout=5 # s

[comic]
    appids_str="1,2,3,4,6" # 现总的appid
